---
abstract: 'perl bindings for libxcb'
author:
  - 'Michael Stapelberg, <michael+xcb@stapelberg.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.2
  Test::Deep: 0
  Test::More: 0
  XSLoader: 0.08
configure_requires:
  ExtUtils::MakeMaker: 6.42
  ExtUtils::PkgConfig: 0.00
  List::Util: 0.00
  XML::Simple: 0.00
  autodie: 0.00
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: X11-XCB
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  Try::Tiny: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_001
