---
abstract: 'perl bindings for libxcb'
author:
  - 'Michael Stapelberg, <michael+xcb@stapelberg.de>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 3.18
  XS::Object::Magic: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: X11-XCB
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dump: 0
  Mouse: 0
  MouseX::NativeTraits: 0
  Try::Tiny: 0
  XML::Descent: 0
  XML::Simple: 0
  XSLoader: 0.02
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://code.stapelberg.de/X11-XCB
version: '0.15'
